### ISSUE TITLE
incorrect url for smilies

### ISSUE THREAD

**Issue by andrewjs18** [dragonexpert/Trade-Feedback#10]
Hi,

when you view your trader feedback page, it'll log an error because the smilies image location is wrong - it appears to be duplicating the url:

http://mysite.com/18/http://mysite.com/18/images/smilies/smile.gif

error in log:

[Thu Jul 16 15:03:22 2015] [error] [client IP] File does not exist: public_html/18/http:, referer: http://mysite.com/18/tradefeedback.php

**Comment by dragonexpert** [comment]
I will have to look into this.  Thanks for bringing it to my attention.

**Comment by andrewjs18** [comment]
no problem.  

as an aside, jnschrag brought some very nice feature additions to the plugin.  I'm going to test them tonight.

**Comment by leefish** [comment]
I added this in my pull request to @jnschrag . @dragonexpert , I know I am marked as a collaborator, but that is only for templates. All commits I will leave with you if that is ok.

**Comment by jnschrag** [comment]
Leefish's fix was added in PR https://github.com/dragonexpert/Trade-Feedback/pull/14

Going to remark this as closed.
