### ISSUE TITLE
feedback disappears when you try to edit it

### ISSUE THREAD

**Issue by andrewjs18** [dragonexpert/Trade-Feedback#11]
if you try to edit feedback that was already given, it wipes out any text that was left in the comment field.  for example:

![198 jul 19](https://cloud.githubusercontent.com/assets/2748980/8767709/46ae8204-2e33-11e5-8ee5-7c985145b5e2.jpg)

![199 jul 19](https://cloud.githubusercontent.com/assets/2748980/8767710/56bdc6c8-2e33-11e5-99e9-9b75d36fe1d4.jpg)

**Comment by leefish** [comment]
The issue is here 
https://github.com/dragonexpert/Trade-Feedback/blob/master/tradefeedback.php#L454

@dragonexpert  the feedback comments are the input, so of course the field is empty on load. How do you want to handle this?

**Comment by dragonexpert** [comment]
$mybb->input['comments'] should be changed to $feedback['comments']
