### ISSUE TITLE
breadcrumb issue when editing your own feedback

### ISSUE THREAD

**Issue by andrewjs18** [dragonexpert/Trade-Feedback#12]
I've only been able to duplicate this issue when I'm editing feedback on my own profile - if I edit another user's feedback, the breadcrumb displays properly.  I tested this in firefox and chrome:

![197 jul 19](https://cloud.githubusercontent.com/assets/2748980/8767735/171c32ec-2e34-11e5-947d-056c2fd71afc.jpg)
it should show andrewjs18's Profile / andrewjs18's Reputations
also, as an aside, it should say Feedback instead of Reputation...

**Comment by leefish** [comment]
This was actually a theme error (a common one): the link for the members profile in the header did not have the uid in the url. By fixing the link to be

"/member.php?action=profile&amp;uid={$mybb->user['uid']}"

the "issue" is fixed.

**Comment by dragonexpert** [comment]
So can I safely close this?

**Comment by leefish** [comment]
I say close it.
