### ISSUE TITLE
Update Language File

### ISSUE THREAD

**Issue by jnschrag** [dragonexpert/Trade-Feedback#13]
I created a language file for the MyAlerts and Report Center integration, but the rest of the text used in the plugin should be added to the language function instead of being hardcoded into the templates.

**Comment by dragonexpert** [comment]
I agree with this.

**Comment by leefish** [comment]
Also agree - is that something you will integrate @jnschrag ?

**Comment by jnschrag** [comment]
Yeah, I can work on updating the language file this week.

**Comment by jnschrag** [comment]
I'll work on this after @leefish has done the updated templates so we don't have any repeated work.

**Comment by leefish** [comment]
Ok, I will upload all the templates, then you can add the language strings to the templates. Is that correct?

**Comment by jnschrag** [comment]
Yep!

**Comment by leefish** [comment]
Ok, templates are added :)
 There are some hardcoded strings in tradefeedback php but I guess you knew that :)

**Comment by jnschrag** [comment]
Thanks! It's looking pretty good. I'm working on the language stuff right now and should have that finished today.

**Comment by jnschrag** [comment]
Fixed by #29.
