### ISSUE TITLE
error when accessing plugins page

### ISSUE THREAD

**Issue by andrewjs18** [dragonexpert/Trade-Feedback#20]
when I try to access my plugins page, it's logging the following error:

[20-Jul-2015 19:31:45 GMT] PHP Fatal error:  Call to a member function get_input() on a non-object in /public_html/inc/plugins/trader.php on line 537

**Comment by dragonexpert** [comment]
I think I forgot to globalize $mybb.  Will have it patched in a few minutes.

**Comment by andrewjs18** [comment]
thanks!

**Comment by dragonexpert** [comment]
Fixed.

**Comment by andrewjs18** [comment]
works great.  thanks again!
