### ISSUE TITLE
Template changes

### ISSUE THREAD

**Issue by leefish** [dragonexpert/Trade-Feedback#21]
I originally offered to do template changes for the plugin. I can still do that. I did make a full set of "bootstrap templates" (uses some bits of bootstrap grid and styling) for DFS, but those were really for that forum. 

link: http://damnfineshave.com/tradefeedback.php?action=view&uid=4

I can make the templates look a bit more in MyBB default style, but how can we handle any extra css I might need?

**Comment by Eldenroot** [comment]
+1 - thx!

**Comment by dragonexpert** [comment]
We write a new stylesheet.

**Comment by leefish** [comment]
![trader](https://cloud.githubusercontent.com/assets/1857551/8850569/6d5a0234-3149-11e5-8a84-e9852e809a93.JPG)

First template

**Comment by Eldenroot** [comment]
what about to shown percentages over mouse hover?

**Comment by leefish** [comment]
The percentages are not accessible in the template as far as I know so that would have to be a plugin enhancement.

**Comment by leefish** [comment]
This is the extra css so far, as you can see, it is mainly to style the dl list for the reputation overview and a couple of helpers to mimic MyBB tables.

https://gist.github.com/leefish/a799b57eeeda0004bbb5

**Comment by leefish** [comment]
There is an issue with the way the feedback details table is built up. 

Example:

![hardcode](https://cloud.githubusercontent.com/assets/1857551/8852344/f9185270-3154-11e5-97c1-3bc6d80ec010.JPG)

As you can see, the details column and detail link are hardcoded as table elements. We can of course adjust the td class to tcat, but the whole design is forced to a table layout by that hardcoded html styling in the php code.

It is actually going to be a similar issue regarding reports; a guest can view but cant report; that means that a guest should not be able to see that column at all, which means it needs to have permissions for the table th and td for that column.

MyBB core handles a similar problem in the forumdisplay: the table elements that depend on permissions are templated out separately and the permissions applied for visibility. The templates I refer to in core are ratings and the inline moderation column.

What approach should we take?

**Comment by dragonexpert** [comment]
The detail column we can have be a separate template and assign a variable.  The links I think we can hard code instead of a new template as long as it actually checks permissions.

**Comment by leefish** [comment]
By the links do you mean the last column? I think the whole column needs to be hidden if a guest views the page, the only link they would see is report, and then clicking it would take them to an error page. Better to not show it at all.

It might actually be better to have the table view have two templates? One for the overview, one for the detail. 

My main thing is to avoid the code forcing layout.

https://github.com/dragonexpert/Trade-Feedback/blob/master/tradefeedback.php#L135
https://github.com/dragonexpert/Trade-Feedback/blob/master/tradefeedback.php#L160
https://github.com/dragonexpert/Trade-Feedback/blob/master/tradefeedback.php#L210
https://github.com/dragonexpert/Trade-Feedback/blob/master/tradefeedback.php#L243

**Comment by leefish** [comment]
This is now uploaded - I was not sure how to add the stylesheet so I have left a link to a gist

**Comment by leefish** [comment]
css now added with commit: https://github.com/dragonexpert/Trade-Feedback/pull/35
