### ISSUE TITLE
White Page on Install

### ISSUE THREAD

**Issue by leefish** [dragonexpert/Trade-Feedback#24]
I just tried installing this on my testboard; php 5.3.29, mybb 1.8.5 , my alerts not installed and got a white page on the forum. When I deactivated etc then the forum "came back". 

What are the minimum requirements on this plugin?

**Comment by dragonexpert** [comment]
Here's the error I get: Fatal error: Class 'MybbStuff_MyAlerts_AlertFormatterManager' not found in /home/superla9/public_html/forums/inc/plugins/trader.php on line 448.
