### ISSUE TITLE
Member Profile Template Not Changed

### ISSUE THREAD

**Issue by dragonexpert** [dragonexpert/Trade-Feedback#25]
The member_profile template should be changed on activate and deactivate.

**Comment by leefish** [comment]
I agree, but isnt there a bug or some such thing with the find replace function? I have seen a lot of reports about it with MyAlerts.

**Comment by dragonexpert** [comment]
It is best we use the find_replace_templatesets function because that is the best we have.  We can also make sure to include the instructions for template changes in case it doesn't work due to custom theme.
