### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by leefish** [dragonexpert/Trade-Feedback#26]
The pagination appears to not paginate. Try setting the pagination to say 5 per page, have 7 feedbacks, view all feedback,click on page 2, the url changes but the table content does not (ie only the first page results show). It did not have this issue on the 1.6 version.

**Comment by dragonexpert** [comment]
Leefish can you test this?

**Comment by leefish** [comment]
Yes I will, but it will be tomorrow :)

**Comment by andrewjs18** [comment]
I'll test this tonight.

**Comment by andrewjs18** [comment]
just tested this by setting the perpage = 3 and it seems to work as intended:

![198 jul 25](https://cloud.githubusercontent.com/assets/2748980/8891451/5bd3c83c-32f8-11e5-8634-deb29b69fe5f.jpg)

![199 jul 25](https://cloud.githubusercontent.com/assets/2748980/8891453/61970072-32f8-11e5-93b0-1deaa76a11c5.jpg)

**Comment by dragonexpert** [comment]
That's good.
