### ISSUE TITLE
Feedback not submitting without MyAlerts

### ISSUE THREAD

**Issue by leefish** [dragonexpert/Trade-Feedback#30]
I have been testing the new templates etc on my test board and DFS; on my testboard with no MyAlerts the feedback form does not submit; it does submit on DFS with MyAlerts..

**Comment by dragonexpert** [comment]
I see the issue.  trader_myalerts is called without verifying that the class exists thus its a fatal PHP error.

**Comment by dragonexpert** [comment]
Test the changes I made.

**Comment by andrewjs18** [comment]
no issue submitting feedback without myalerts installed and it's not registering any php errors.
