### ISSUE TITLE
SQL error on tradefeedback.php

### ISSUE THREAD

**Issue by leefish** [dragonexpert/Trade-Feedback#31]
If the trader plugin is uninstalled then visiting the tradefeedback url gives an SQL error (table does not exist).

**Comment by dragonexpert** [comment]
I guess the best way is to use the error function.

**Comment by andrewjs18** [comment]
if I deactivate, uninstall trade feedback and then try visiting a trader feedback link, the page is white and it logs the following error: 

[Sat Jul 25 17:49:13 2015] [error] [client IP] FastCGI: server "/home/www-data/web/php-fastcgi" stderr: PHP Fatal error:  Call to undefined function trader_is_installed() in /public_html/18/tradefeedback.php on line 6, referer: http://andrewshemo.com/18/tradefeedback.php

**Comment by dragonexpert** [comment]
I thought it loaded all plugin files in global.php. Easy fix though.

**Comment by dragonexpert** [comment]
Should be fixed now.

**Comment by andrewjs18** [comment]
retested again.  this is the error it'll show:

Trade Feedback is not installed.

no errors in my log.

**Comment by dragonexpert** [comment]
That is the intended behavior if Trade Feedback is not installed.

**Comment by andrewjs18** [comment]
I figured.  I'd consider it fixed then.
